[project]
name = "dummy-service"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.117.1",
    "gunicorn>=23.0.0",
    "pydantic>=2.11.9",
    "pymongo>=4.15.1",
    "uvicorn>=0.37.0",
]
